import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Navbar";

const danaRegular = localFont({
  src: "../public/fonts/Dana/woff2/DanaFaNum-Regular.woff2",
  variable: "--font-dana-regular",
});
const danaMedium = localFont({
  src: "../public/fonts/Dana/woff2/DanaFaNum-Medium.woff2",
  variable: "--font-dana-medium",
});
const danaDemiBold = localFont({
  src: "../public/fonts/Dana/woff2/DanaFaNum-DemiBold.woff2",
  variable: "--font-dana-demibold",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" data-theme="sunset">
      <body className={`${danaRegular.variable} text-zinc-50`}>
          <section className="flex">
            <Navbar />
            <main className="p-10 w-full h-screen overflow-auto">{children}</main>
          </section>
      </body>
    </html>
  );
}
